### ISSUE TITLE
Swift 3 - Dynamic color not compiling with SnappingStepper Cocoapods installation

### ISSUE THREAD

**Issue by mvitolo** [yannickl/SnappingStepper#13]
When installing via Cocoapods SnappingStepper the Dynamic Color pod does not compile.

<img width="258" alt="dynamiccolorswift3" src="https://cloud.githubusercontent.com/assets/6552122/19035526/3e309bb0-896a-11e6-9db3-14e01ec4e22b.png">

**Comment by yannickl** [comment]
Which version are you trying to install?

**Comment by mvitolo** [comment]
pod 'SnappingStepper', '~> 2.4.0'

here my podfile

``` ruby
platform :ios, '8.0'
use_frameworks!

target 'myApp' do
[other pods]
pod 'SnappingStepper', '~> 2.4.0'
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

**Comment by yannickl** [comment]
Ok, so you are working with Xcode 8 and Swift 3?

If so, I didn't pushed the swift3 version to Cocoapods because the API will be updated. But you can already use it by copying this line:

``` ruby
pod 'SnappingStepper', :git => 'https://github.com/yannickl/SnappingStepper.git', :branch => 'swift3'
```

**Comment by mvitolo** [comment]
wonderful

thanks

**Comment by yannickl** [comment]
You're welcome. 👍

**Comment by gopalkohli** [comment]
when plan to update it to swift 3
