### ISSUE TITLE
Error Rendering SnappingStepper in Storyboard

### ISSUE THREAD

**Issue by milankappen** [yannickl/SnappingStepper#9]
```
> "error: IB Designables: Failed to render instance of SnappingStepper: dlopen(SnappingStepper.framework, 1): Library not loaded: @rpath/DynamicColor.framework/DynamicColor
>   Referenced from: SnappingStepper.framework
>   Reason: image not found"
```

If I use the SnappingStepper in any Storyboard I constantly get the Error Message above...

**Comment by mjrehder** [comment]
I had the same issue when upgrading CocoaPods to version 1.0.1. It seems that there is an issue with IBDesignables. There is a workaround described by neonichu in the thread [https://github.com/CocoaPods/CocoaPods/issues/5334](url) which suggests to add the following to your podfile:
`post_install do |installer|`
 `installer.pods_project.targets.each do |target|`
 `target.build_configurations.each do |config|`
 `config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'`
 `end`
 `end`
`end`
Then re-run the `pod update`.
It worked for me. Please try it.

**Comment by milankappen** [comment]
Thanks a lot - that worked!
